/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 5.28.3
 * source: helios/chronos/v1/genesis.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./../../../gogoproto/gogo";
import * as dependency_2 from "./params";
import * as dependency_3 from "./schedule";
import * as pb_1 from "google-protobuf";
export namespace helios.chronos.v1 {
    export class GenesisState extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            schedule_list?: dependency_3.helios.chronos.v1.Schedule[];
            params?: dependency_2.helios.chronos.v1.Params;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("schedule_list" in data && data.schedule_list != undefined) {
                    this.schedule_list = data.schedule_list;
                }
                if ("params" in data && data.params != undefined) {
                    this.params = data.params;
                }
            }
        }
        get schedule_list() {
            return pb_1.Message.getRepeatedWrapperField(this, dependency_3.helios.chronos.v1.Schedule, 1) as dependency_3.helios.chronos.v1.Schedule[];
        }
        set schedule_list(value: dependency_3.helios.chronos.v1.Schedule[]) {
            pb_1.Message.setRepeatedWrapperField(this, 1, value);
        }
        get params() {
            return pb_1.Message.getWrapperField(this, dependency_2.helios.chronos.v1.Params, 2) as dependency_2.helios.chronos.v1.Params;
        }
        set params(value: dependency_2.helios.chronos.v1.Params) {
            pb_1.Message.setWrapperField(this, 2, value);
        }
        get has_params() {
            return pb_1.Message.getField(this, 2) != null;
        }
        static fromObject(data: {
            schedule_list?: ReturnType<typeof dependency_3.helios.chronos.v1.Schedule.prototype.toObject>[];
            params?: ReturnType<typeof dependency_2.helios.chronos.v1.Params.prototype.toObject>;
        }): GenesisState {
            const message = new GenesisState({});
            if (data.schedule_list != null) {
                message.schedule_list = data.schedule_list.map(item => dependency_3.helios.chronos.v1.Schedule.fromObject(item));
            }
            if (data.params != null) {
                message.params = dependency_2.helios.chronos.v1.Params.fromObject(data.params);
            }
            return message;
        }
        toObject() {
            const data: {
                schedule_list?: ReturnType<typeof dependency_3.helios.chronos.v1.Schedule.prototype.toObject>[];
                params?: ReturnType<typeof dependency_2.helios.chronos.v1.Params.prototype.toObject>;
            } = {};
            if (this.schedule_list != null) {
                data.schedule_list = this.schedule_list.map((item: dependency_3.helios.chronos.v1.Schedule) => item.toObject());
            }
            if (this.params != null) {
                data.params = this.params.toObject();
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.schedule_list.length)
                writer.writeRepeatedMessage(1, this.schedule_list, (item: dependency_3.helios.chronos.v1.Schedule) => item.serialize(writer));
            if (this.has_params)
                writer.writeMessage(2, this.params, () => this.params.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): GenesisState {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new GenesisState();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.schedule_list, () => pb_1.Message.addToRepeatedWrapperField(message, 1, dependency_3.helios.chronos.v1.Schedule.deserialize(reader), dependency_3.helios.chronos.v1.Schedule));
                        break;
                    case 2:
                        reader.readMessage(message.params, () => message.params = dependency_2.helios.chronos.v1.Params.deserialize(reader));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): GenesisState {
            return GenesisState.deserialize(bytes);
        }
    }
}
